-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 18:36:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruzkumnikSVP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruzkumnikSVP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruzkumnikSVP` DEFAULT CHARACTER SET utf8 ;
USE `pruzkumnikSVP` ;

-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`skola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`skola` (
  `skolaID` INT NOT NULL AUTO_INCREMENT,
  `jmenoSkoly` VARCHAR(45) NULL,
  PRIMARY KEY (`skolaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`svp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`svp` (
  `svpID` INT NOT NULL,
  `jmenoSVP` VARCHAR(45) NULL,
  `popisSVP` LONGTEXT NULL,
  `skola_skolaID` INT NOT NULL,
  PRIMARY KEY (`svpID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`cil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`cil` (
  `cilID` INT NOT NULL,
  `jmenoCile` VARCHAR(45) NULL,
  `popisCile` LONGTEXT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`cilID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`vzdelavaciObor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`vzdelavaciObor` (
  `vzdelavaciOborID` INT NOT NULL,
  `jmenoOboru` VARCHAR(45) NULL,
  `popisOboru` LONGTEXT NULL,
  `rodicovskyVzdelavaciOborID` INT NOT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`vzdelavaciOborID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`typObsahu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`typObsahu` (
  `typObsahuID` INT NOT NULL,
  `jmenoTypu` VARCHAR(45) NULL,
  `popisTypu` LONGTEXT NULL,
  PRIMARY KEY (`typObsahuID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`vzdelavaciObsah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`vzdelavaciObsah` (
  `vzdelavaciObsahID` INT NOT NULL,
  `jmenoObsahu` VARCHAR(45) NULL,
  `popisObsahu` LONGTEXT NULL,
  `typObsahu_typObsahuID` INT NOT NULL,
  `rodicovskyVzdelavaciObsahID` INT NOT NULL,
  `cil_cilID` INT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`vzdelavaciObsahID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`typAktivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`typAktivity` (
  `typAktivityID` INT NOT NULL,
  `jmenoTypu` VARCHAR(45) NULL,
  `popisTypu` LONGTEXT NULL,
  PRIMARY KEY (`typAktivityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`vzdelavaciAktivita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`vzdelavaciAktivita` (
  `vzdelavaciAktivitaID` INT NOT NULL,
  `jmenoAktivity` VARCHAR(45) NULL,
  `popisAktivity` VARCHAR(45) NULL,
  `typAktivity_typAktivityID` INT NOT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`vzdelavaciAktivitaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`soucastAktivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`soucastAktivity` (
  `soucastAktivityID` INT NOT NULL,
  `jmenoSoucasti` VARCHAR(45) NULL,
  `popisSoucasti` VARCHAR(45) NULL,
  `vzdelavaciAktivita_vzdelavaciAktivitaID` INT NOT NULL,
  `vzdelavaciObor_vzdelavaciOborID` INT NOT NULL,
  `vzdelavaciObsah_vzdelavaciObsahID` INT NOT NULL,
  PRIMARY KEY (`soucastAktivityID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
