-- MySQL Script generated by MySQL Workbench
-- Tue Dec 31 09:45:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruzkumnikSVP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruzkumnikSVP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruzkumnikSVP` DEFAULT CHARACTER SET utf8 ;
USE `pruzkumnikSVP` ;

-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`skola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`skola` (
  `skolaID` INT NOT NULL AUTO_INCREMENT,
  `jmenoSkoly` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`skolaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`svp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`svp` (
  `svpID` INT NOT NULL AUTO_INCREMENT,
  `jmenoSVP` VARCHAR(200) NOT NULL,
  `popisSVP` LONGTEXT NULL,
  `skola_skolaID` INT NOT NULL,
  PRIMARY KEY (`svpID`),
  CONSTRAINT `fk_svp_skola1`
    FOREIGN KEY (`skola_skolaID`)
    REFERENCES `pruzkumnikSVP`.`skola` (`skolaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_svp_skola1_idx` ON `pruzkumnikSVP`.`svp` (`skola_skolaID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`cil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`cil` (
  `cilID` INT NOT NULL AUTO_INCREMENT,
  `jmenoCile` VARCHAR(200) NOT NULL,
  `popisCile` LONGTEXT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`cilID`),
  CONSTRAINT `fk_cil_svp1`
    FOREIGN KEY (`svp_svpID`)
    REFERENCES `pruzkumnikSVP`.`svp` (`svpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_cil_svp1_idx` ON `pruzkumnikSVP`.`cil` (`svp_svpID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`vzdelavaciObor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`vzdelavaciObor` (
  `vzdelavaciOborID` INT NOT NULL AUTO_INCREMENT,
  `jmenoOboru` VARCHAR(200) NULL,
  `popisOboru` LONGTEXT NULL,
  `rodicovskyVzdelavaciOborID` INT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`vzdelavaciOborID`),
  CONSTRAINT `fk_vzdelavaciObor_vzdelavaciObor1`
    FOREIGN KEY (`rodicovskyVzdelavaciOborID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciObor` (`vzdelavaciOborID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vzdelavaciObor_svp1`
    FOREIGN KEY (`svp_svpID`)
    REFERENCES `pruzkumnikSVP`.`svp` (`svpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_vzdelavaciObor_vzdelavaciObor1_idx` ON `pruzkumnikSVP`.`vzdelavaciObor` (`rodicovskyVzdelavaciOborID` ASC);

CREATE INDEX IF NOT EXISTS `fk_vzdelavaciObor_svp1_idx` ON `pruzkumnikSVP`.`vzdelavaciObor` (`svp_svpID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`vzdelavaciObsah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`vzdelavaciObsah` (
  `vzdelavaciObsahID` INT NOT NULL AUTO_INCREMENT,
  `jmenoObsahu` VARCHAR(200) NOT NULL,
  `popisObsahu` LONGTEXT NULL,
  `rodicovskyVzdelavaciObsahID` INT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`vzdelavaciObsahID`),
  CONSTRAINT `fk_vzdelavaciObsah_vzdelavaciObsah1`
    FOREIGN KEY (`rodicovskyVzdelavaciObsahID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciObsah` (`vzdelavaciObsahID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vzdelavaciObsah_svp1`
    FOREIGN KEY (`svp_svpID`)
    REFERENCES `pruzkumnikSVP`.`svp` (`svpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_vzdelavaciObsah_vzdelavaciObsah1_idx` ON `pruzkumnikSVP`.`vzdelavaciObsah` (`rodicovskyVzdelavaciObsahID` ASC);

CREATE INDEX IF NOT EXISTS `fk_vzdelavaciObsah_svp1_idx` ON `pruzkumnikSVP`.`vzdelavaciObsah` (`svp_svpID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`typAktivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`typAktivity` (
  `typAktivityID` INT NOT NULL AUTO_INCREMENT,
  `jmenoTypu` VARCHAR(200) NOT NULL,
  `popisTypu` LONGTEXT NULL,
  PRIMARY KEY (`typAktivityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`vzdelavaciAktivita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`vzdelavaciAktivita` (
  `vzdelavaciAktivitaID` INT NOT NULL AUTO_INCREMENT,
  `jmenoAktivity` VARCHAR(200) NOT NULL,
  `popisAktivity` LONGTEXT NULL,
  `typAktivity_typAktivityID` INT NOT NULL,
  `svp_svpID` INT NOT NULL,
  PRIMARY KEY (`vzdelavaciAktivitaID`),
  CONSTRAINT `fk_vzdelavaciAktivita_typAktivity`
    FOREIGN KEY (`typAktivity_typAktivityID`)
    REFERENCES `pruzkumnikSVP`.`typAktivity` (`typAktivityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vzdelavaciAktivita_svp1`
    FOREIGN KEY (`svp_svpID`)
    REFERENCES `pruzkumnikSVP`.`svp` (`svpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_vzdelavaciAktivita_typAktivity_idx` ON `pruzkumnikSVP`.`vzdelavaciAktivita` (`typAktivity_typAktivityID` ASC);

CREATE INDEX IF NOT EXISTS `fk_vzdelavaciAktivita_svp1_idx` ON `pruzkumnikSVP`.`vzdelavaciAktivita` (`svp_svpID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`rocnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`rocnik` (
  `rocnikID` INT NOT NULL AUTO_INCREMENT,
  `jmenoRocniku` VARCHAR(45) NOT NULL,
  `popisRocniku` LONGTEXT NULL,
  PRIMARY KEY (`rocnikID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`pomucka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`pomucka` (
  `pomuckaID` INT NOT NULL AUTO_INCREMENT,
  `jmenoPomucky` VARCHAR(45) NOT NULL,
  `popisPomucky` LONGTEXT NULL,
  PRIMARY KEY (`pomuckaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`soucastAktivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`soucastAktivity` (
  `soucastAktivityID` INT NOT NULL AUTO_INCREMENT,
  `jmenoSoucasti` VARCHAR(200) NOT NULL,
  `popisSoucasti` LONGTEXT NULL,
  `vzdelavaciAktivita_vzdelavaciAktivitaID` INT NOT NULL,
  `vzdelavaciObor_vzdelavaciOborID` INT NOT NULL,
  `vzdelavaciObsah_vzdelavaciObsahID` INT NOT NULL,
  `rocnik_rocnikID` INT NOT NULL,
  `pomucka_pomuckaID` INT NULL,
  PRIMARY KEY (`soucastAktivityID`),
  CONSTRAINT `fk_soucastAktivity_vzdelavaciAktivita1`
    FOREIGN KEY (`vzdelavaciAktivita_vzdelavaciAktivitaID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciAktivita` (`vzdelavaciAktivitaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soucastAktivity_vzdelavaciObor1`
    FOREIGN KEY (`vzdelavaciObor_vzdelavaciOborID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciObor` (`vzdelavaciOborID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soucastAktivity_vzdelavaciObsah1`
    FOREIGN KEY (`vzdelavaciObsah_vzdelavaciObsahID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciObsah` (`vzdelavaciObsahID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soucastAktivity_rocnik1`
    FOREIGN KEY (`rocnik_rocnikID`)
    REFERENCES `pruzkumnikSVP`.`rocnik` (`rocnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soucastAktivity_pomucka1`
    FOREIGN KEY (`pomucka_pomuckaID`)
    REFERENCES `pruzkumnikSVP`.`pomucka` (`pomuckaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_soucastAktivity_vzdelavaciAktivita1_idx` ON `pruzkumnikSVP`.`soucastAktivity` (`vzdelavaciAktivita_vzdelavaciAktivitaID` ASC);

CREATE INDEX IF NOT EXISTS `fk_soucastAktivity_vzdelavaciObor1_idx` ON `pruzkumnikSVP`.`soucastAktivity` (`vzdelavaciObor_vzdelavaciOborID` ASC);

CREATE INDEX IF NOT EXISTS `fk_soucastAktivity_vzdelavaciObsah1_idx` ON `pruzkumnikSVP`.`soucastAktivity` (`vzdelavaciObsah_vzdelavaciObsahID` ASC);

CREATE INDEX IF NOT EXISTS `fk_soucastAktivity_rocnik1_idx` ON `pruzkumnikSVP`.`soucastAktivity` (`rocnik_rocnikID` ASC);

CREATE INDEX IF NOT EXISTS `fk_soucastAktivity_pomucka1_idx` ON `pruzkumnikSVP`.`soucastAktivity` (`pomucka_pomuckaID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`plneniCile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`plneniCile` (
  `plneniCileID` INT NOT NULL AUTO_INCREMENT,
  `popisPlneniCile` LONGTEXT NULL,
  `cil_cilID` INT NOT NULL,
  `vzdelavaciObsah_vzdelavaciObsahID` INT NOT NULL,
  PRIMARY KEY (`plneniCileID`),
  CONSTRAINT `fk_plneniCile_cil1`
    FOREIGN KEY (`cil_cilID`)
    REFERENCES `pruzkumnikSVP`.`cil` (`cilID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plneniCile_vzdelavaciObsah1`
    FOREIGN KEY (`vzdelavaciObsah_vzdelavaciObsahID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciObsah` (`vzdelavaciObsahID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_plneniCile_cil1_idx` ON `pruzkumnikSVP`.`plneniCile` (`cil_cilID` ASC);

CREATE INDEX IF NOT EXISTS `fk_plneniCile_vzdelavaciObsah1_idx` ON `pruzkumnikSVP`.`plneniCile` (`vzdelavaciObsah_vzdelavaciObsahID` ASC);


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`mesic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`mesic` (
  `mesicID` INT NOT NULL AUTO_INCREMENT,
  `jmenoMesice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mesicID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruzkumnikSVP`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruzkumnikSVP`.`tema` (
  `temaID` INT NOT NULL AUTO_INCREMENT,
  `jmenoTematu` VARCHAR(45) NOT NULL,
  `popisTematu` LONGTEXT NULL,
  `rocnik_rocnikID` INT NOT NULL,
  `vzdelavaciObor_vzdelavaciOborID` INT NOT NULL,
  `mesicID_zacatek` INT NOT NULL,
  `mesicID_konec` INT NOT NULL,
  PRIMARY KEY (`temaID`),
  CONSTRAINT `fk_tema_rocnik1`
    FOREIGN KEY (`rocnik_rocnikID`)
    REFERENCES `pruzkumnikSVP`.`rocnik` (`rocnikID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tema_vzdelavaciObor1`
    FOREIGN KEY (`vzdelavaciObor_vzdelavaciOborID`)
    REFERENCES `pruzkumnikSVP`.`vzdelavaciObor` (`vzdelavaciOborID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tema_mesic1`
    FOREIGN KEY (`mesicID_zacatek`)
    REFERENCES `pruzkumnikSVP`.`mesic` (`mesicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tema_mesic2`
    FOREIGN KEY (`mesicID_konec`)
    REFERENCES `pruzkumnikSVP`.`mesic` (`mesicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX IF NOT EXISTS `fk_tema_rocnik1_idx` ON `pruzkumnikSVP`.`tema` (`rocnik_rocnikID` ASC);

CREATE INDEX IF NOT EXISTS `fk_tema_vzdelavaciObor1_idx` ON `pruzkumnikSVP`.`tema` (`vzdelavaciObor_vzdelavaciOborID` ASC);

CREATE INDEX IF NOT EXISTS `fk_tema_mesic1_idx` ON `pruzkumnikSVP`.`tema` (`mesicID_zacatek` ASC);

CREATE INDEX IF NOT EXISTS `fk_tema_mesic2_idx` ON `pruzkumnikSVP`.`tema` (`mesicID_konec` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
